### ISSUE TITLE
Can't run on the linode server

### ISSUE THREAD

**Issue by sawalls** [sawalls/teledraw2#37]
```/home/swalls/apps/teledraw2/server/routes.js:276
            s3.getSignedUrl('putObject', s3Params, (err, reqUrl) => {
                                                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/swalls/apps/teledraw2/server/server.js:13:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3```

Either install a new version of nodejs on the server, or start doing docker stuff!

**Comment by sawalls** [comment]
Got it running in the docker branch.
